### ISSUE TITLE
GLASC Support

### ISSUE THREAD

**Issue by alexivanov** [KMayne/pub-crawl-tool#12]
It would be good if there is support for GLASC 2018. :) 

Thanks1

**Comment by KMayne** [comment]
Required for this:
- https://github.com/KMayne/pub-crawl-tool/issues/5
- Branding changes?

**Comment by alexivanov** [comment]
Possible to make a branch with config & branding changes? Can be merged in the future when routes are not hardcoded.

**Comment by ThomasBower** [comment]
Fixed in #17.
